# Generated by Django 4.1.2 on 2023-12-29 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_mention_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
