# Generated by Django 4.1.2 on 2024-01-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0013_reshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reshare',
        ),
    ]
