# Generated by Django 4.1.2 on 2024-01-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0015_post_reshare_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reshare_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_from',
        ),
    ]
