# Generated by Django 4.1.2 on 2024-01-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0021_post_reshared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
