# Generated by Django 4.1.2 on 2024-01-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0022_rename_user_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
