# Generated by Django 4.1.2 on 2024-01-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0024_postmedia_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Your date of birth', null=True),
        ),
    ]
