# Generated by Django 4.1.2 on 2024-01-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0025_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
