# Generated by Django 4.1.2 on 2024-01-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0026_remove_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
