# Generated by Django 4.1.2 on 2024-01-06 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0028_group_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time the group was created.'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who created the group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='Moderators of this group.', related_name='group_moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of this group.', related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
