# Generated by Django 4.1.2 on 2024-01-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0029_group_bio_group_created_group_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
