# Generated by Django 4.1.2 on 2024-01-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0034_groupcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='group_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='social_network.grouppost'),
        ),
    ]
