# Generated by Django 4.1.2 on 2024-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0035_remove_groupcomment_likes_remove_groupcomment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Indicates whether the group is private or public.'),
        ),
    ]
