# Generated by Django 4.1.2 on 2024-01-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0037_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
