# Generated by Django 4.1.2 on 2024-01-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0041_rename_is_reshared_post_reshared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
