# Generated by Django 4.1.2 on 2024-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0042_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='image',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
