# Generated by Django 4.1.2 on 2024-01-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0044_remove_grouppost_tags_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
